apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sabnzbd-operator
  template:
    metadata:
      labels:
        name: sabnzbd-operator
    spec:
      serviceAccountName: sabnzbd-operator
      containers:
        - name: sabnzbd-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - sabnzbd-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sabnzbd-operator"
