apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "sabnzbd.parflesh.github.io/v1alpha1",
          "kind": "SABnzbd",
          "metadata": {
            "name": "example-sabnzbd"
          },
          "spec": {
            "size": 3
          }
        }
      ]
    capabilities: Basic Install
  name: sabnzbd-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: SABnzbd is the Schema for the sabnzbds API
      displayName: SABnzbd
      kind: SABnzbd
      name: sabnzbds.sabnzbd.parflesh.github.io
      resources:
      - kind: Deployment
        name: sabnzbd-operator
        version: v1
      - kind: Service
        name: sabnzbd-operator
        version: v1
      specDescriptors:
      - description: Additional Volumes to be mounted in SABnzbd container
        displayName: Additional Volumes
        path: additionalVolumes
      - description: SABnzbd Config Volume mounted to /config
        displayName: Config Volume
        path: configVolume
      - description: Stop automatic updates when hash for image tag changes
        displayName: Disable Image Updates
        path: disableUpdates
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: 'Container image capable of running SABnzbd (Default: quay.io/parflesh/sabnzbd:latest)'
        displayName: Container Image
        path: image
      - description: Image pull secret for private container images
        displayName: Image Pull Secret
        path: imagePullSecret
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:Secret
      - description: Priority Class Name
        displayName: Priority Class Name
        path: priorityClassName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Run as Group Id
        displayName: GroupID
        path: runAsGroup
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      - description: Run as User Id
        displayName: User ID
        path: runAsUser
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      - description: 'Time to wait between checking resource status (Default: 1m)'
        displayName: Watch Frequency
        path: watchFrequency
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      statusDescriptors:
      - description: Desired Image hash for container
        displayName: Image
        path: image
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Phase
        displayName: Phase
        path: phase
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.phase
      - description: Reason
        displayName: Reason
        path: reason
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.phase:reason
      version: v1alpha1
  description: Placeholder description
  displayName: Sabnzbd Operator
  install:
    spec:
      deployments:
      - name: sabnzbd-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: sabnzbd-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: sabnzbd-operator
            spec:
              containers:
              - command:
                - sabnzbd-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: sabnzbd-operator
                image: quay.io/parflesh/sabnzbd-operator:0.0.1
                imagePullPolicy: Always
                name: sabnzbd-operator
                resources: {}
              serviceAccountName: sabnzbd-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - sabnzbd-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - sabnzbd.parflesh.github.io
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: sabnzbd-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - SABnzbd
  maintainers:
  - email: parflesh@gmail.com
    name: ParFlesh
  maturity: alpha
  provider:
    name: ParFlesh
    url: https://github.com/ParFlesh
  replaces: sabnzbd-operator.v0.0.0
  version: 0.0.1
